bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

pro/urls.py
from django.urls import path

from .views import MembershipSelectView, PaymentView

app_name = 'pro'

urlpatterns = [
    path('', MembershipSelectView.as_view(), name='select')
]

wellness_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('blog/', include('blog.urls')),
    path('videos/', include('videos.urls')),
    path('pro_payment/', include('pro_payment.urls')),
    path('users/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videos/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from allauth.account.signals import email_confirmed

import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

User = get_user_model()


class Pricing(models.Model):
    """
    Model sets the price parameters of the video course
    """
    name = models.CharField(max_length=100, null=True, blank=True)  # Basic / Pro
    slug = models.SlugField(null=True)

    def __str__(self):
        return self.name


class Subscription(models.Model):
    """
    Model for subcriptions to manage each
    user subcription and permisions
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE, related_name='subscriptions')
    created = models.DateTimeField(auto_now_add=True)
    stripe_subscription_id = models.CharField(max_length=50)
    status = models.CharField(max_length=100)

    def __str__(self):
        return self.user.email



class Course(models.Model):
    """
    Model to manage and add the courses
    """
    name = models.CharField(max_length=100, null=True, blank=True)
    slug = models.SlugField(unique=True)
    thumbnail = models.ImageField(upload_to="thumbnails/")
    description = models.TextField()

    def __str__(self):
        return self.name

    
    def get_absolute_url(self):
        return reverse("videos:course-detail", kwargs={"slug": self.slug})


class Video(models.Model):
    """
    Model for manageing and adding videos
    using vimeo, can add videos using vimeo id
    on the vimeo dashboard will generate the vimeo id needed
    """
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='videos')
    vimeo_id = models.CharField(max_length=50)
    title = models.CharField(max_length=150)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    order = models.IntegerField(default=1)

    class Meta:
        ordering = ["order"] 

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("videos:video-detail", kwargs={
            "video_slug": self.slug,
            "slug": self.course.slug
        })


def pre_save_course(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)


def pre_save_video(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)


def post_save_user(sender, instance, created, *args, **kwargs):
    if created:
        free_trial_pricing = Pricing.objects.get(name='Free Trial')
        subscription = Subscription.objects.create(
            user=instance, 
            pricing=free_trial_pricing
        )
        stripe_customer = stripe.Customer.create(
            email=instance.email
        )
        stripe_subscription = stripe.Subscription.create(
            customer=stripe_customer['id'],
            items=[{'price': 'price_1HMtRnHeew9pZh4QRDKWiRKq'}]
        )
        print(stripe_subscription)
        subscription.status = stripe_subscription["status"] # trialing
        subscription.stripe_subscription_id = stripe_subscription["id"]
        subscription.save()


post_save.connect(post_save_user, sender=User)
pre_save.connect(pre_save_course, sender=Course)
pre_save.connect(pre_save_video, sender=Video)

pro/views.py
from django.shortcuts import render, redirect, reverse, get_object_or_404
from django.contrib import messages
from django.conf import settings
from django.http import JsonResponse, HttpResponse, HttpResponseRedirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required
from django.views import generic
from django.views.generic import ListView

from .models import Membership, UserMembership, Subscription

import stripe
import json


def get_user_membership(request):
    user_membership_qs = UserMembership.objects.filter(user=request.user)
    if user_membership_qs.exists():
        return user_membership_qs.first()
    return None


def get_user_subscription(request):
    user_subscription_qs = Subscription.objects.filter(
        user_membership=get_user_membership(request))
    if user_subscription_qs.exists():
        user_subscription = user_subscription_qs.first()
        return user_subscription
    return None


def get_selected_membership(request):
    membership_type = request.session['selected_membership_type']
    selected_membership_qs = Membership.objects.filter(
        membership_type=membership_type)
    if selected_membership_qs.exists():
        return selected_membership_qs.first()
    return None


class MembershipSelectView(ListView):
    model = Membership

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(**kwargs)
        current_membership = get_user_membership(self.request)
        context['current_membership'] = str(current_membership.membership)
        return context

    def post(self, request, **kwargs):
        user_membership = get_user_membership(request)
        user_subscription = get_user_subscription(request)
        selected_membership_type = request.POST.get('membership_type')

        selected_membership = Membership.objects.get(
            membership_type=selected_membership_type)

        if user_membership.membership == selected_membership:
            if user_subscription is not None:
                messages.info(request, """You already have this membership. Your
                              next payment is due {}""".format('get this value from stripe'))
                return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

        # assign to the session
        request.session['selected_membership_type'] = selected_membership.membership_type

        return HttpResponseRedirect(reverse('pro:payment'))

    
def PaymentView(request):
    user_membership = get_user_membership(request)
    try:
        selected_membership = get_selected_membership(request)
    except:
        return redirect(reverse("pro:select"))
    publishKey = settings.STRIPE_PUBLIC_KEY
    if request.method == "POST":
        try:
            token = request.POST['stripeToken']

            # UPDATE FOR STRIPE API CHANGE 2018-05-21

            '''
            First we need to add the source for the customer
            '''

            customer = stripe.Customer.retrieve(user_membership.stripe_customer_id)
            customer.source = token # 4242424242424242
            customer.save()

            '''
            Now we can create the subscription using only the customer as we don't need to pass their
            credit card source anymore
            '''

            subscription = stripe.Subscription.create(
                customer=user_membership.stripe_customer_id,
                items=[
                    { "plan": selected_membership.stripe_plan_id },
                ]
            )

            return redirect(reverse('pro:update-transactions',
                                    kwargs={
                                        'subscription_id': subscription.id
                                    }))

        except:
            messages.info(request, "An error has occurred, investigate it in the console")

    context = {
        'publishKey': publishKey,
        'selected_membership': selected_membership
    }

    return render(request, "pro/membership_payment.html", context)

pro/templates/pro/membership_list.html
{% extends 'base.html' %}


{% block content %}
<div class="container" style="padding-top:6rem;">
	<h1>Select a membership</h1>
	<div class="row">
		{% for object in object_list %}
		<div class="col-sm-4 col-md-4">
			<h2>{{ object.membership_type }}</h2>
			<p>Price: ${{ object.price }}<small>/month</small></p>
			<h4>Included Videos</h4>
			<ul>
				{% for video in object.video_set.all %}
					<li>{{ video.title }}</li>
				{% endfor %}
			</ul>
			{% if object.membership_type != 'Free' %}
			<form method="POST" action="{% url 'pro:select' %}">
				{% csrf_token %}
				{% if object.membership_type != current_membership %}
					<button class="btn btn-warning">Select</button>
				{% else %}
					<small>This is your current membership</small>
				{% endif %}
				<input type="hidden" name="membership_type" value="{{ object.membership_type }}">
			</form>			
			{% endif %}	
		</div>
		{% endfor %}
	</div>
</div>



{% endblock content %}

pro/templates/pro/pro-members.html
{% extends "base.html" %}
{% load static %}

{% block content %}


<div class="album py-5 bg-light">

    <div class="container">
        <h1 class="text-center text-black"><strong>Welcome Pro members!</strong></h1>
        </br>
      <div class="row">
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class=" background="#55595c" color="#eceeef" class="card-img-top" text="Thumbnail""> 
            <iframe width="100%" height="225" src="https://www.youtube.com/embed/tgbNymZ7vqY">
            </iframe>
            </div>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          <div class=" background="#55595c" color="#eceeef" class="card-img-top" text="Thumbnail""> 
            <iframe width="100%" height="225" src="https://www.youtube.com/embed/tgbNymZ7vqY">
            </iframe>
            </div>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          <div class=" background="#55595c" color="#eceeef" class="card-img-top" text="Thumbnail""> 
            <iframe width="100%" height="225" src="https://www.youtube.com/embed/tgbNymZ7vqY">
            </iframe>
            </div>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          <div class=" background="#55595c" color="#eceeef" class="card-img-top" text="Thumbnail""> 
            <iframe width="100%" height="225" src="https://www.youtube.com/embed/tgbNymZ7vqY">
            </iframe>
            </div>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          <div class=" background="#55595c" color="#eceeef" class="card-img-top" text="Thumbnail""> 
            <iframe width="100%" height="225" src="https://www.youtube.com/embed/tgbNymZ7vqY">
            </iframe>
            </div>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class=" background="#55595c" color="#eceeef" class="card-img-top" text="Thumbnail""> 
            <iframe width="100%" height="225" src="https://www.youtube.com/embed/tgbNymZ7vqY">
            </iframe>
            </div>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>

        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class=" background="#55595c" color="#eceeef" class="card-img-top" text="Thumbnail""> 
            <iframe width="100%" height="225" src="https://www.youtube.com/embed/tgbNymZ7vqY">
            </iframe>
            </div>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
            <div class=" background="#55595c" color="#eceeef" class="card-img-top" text="Thumbnail""> 
            <iframe width="100%" height="225" src="https://www.youtube.com/embed/tgbNymZ7vqY">
            </iframe>
            </div>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          <div class=" background="#55595c" color="#eceeef" class="card-img-top" text="Thumbnail""> 
            <iframe width="100%" height="225" src="https://www.youtube.com/embed/tgbNymZ7vqY">
            </iframe>
            </div>
            <div class="card-body">
              <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
                </div>
                <small class="text-muted">9 mins</small>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
{% endblock %}

pro/templates/pro/pro.html
{% extends "base.html" %}
{% load static %}
{% block content %}
    <div class="container" style="margin-top:6rem;">
      <div class="header clearfix">
        <h1 class="text-center display-4">Try Wellness Pro unlock the full Wellness experience</h1>
      </div>

      <div class="jumbotron">
        <h2>Pro Membership</h2>
        <p class="lead">Purchase Pro Membership for only $99.</p>
        <a href="#" id="buy_now_btn" class="btn btn-primary">Buy Now</a>
      </div>
    </div>

    <script src="https://js.stripe.com/v3/"></script>

    <script type="text/javascript">
        var stripe = Stripe('{{ stripe_public_key }}');

        const buy_now_button = document.querySelector('#buy_now_btn')

        buy_now_button.addEventListener('click', event => {   
            stripe.redirectToCheckout({
            // Make the id field from the Checkout Session creation API response
            // available to this file, so you can provide it as parameter here
            // instead of the {{CHECKOUT_SESSION_ID}} placeholder.
              sessionId: '{{ session_id }}'
            }).then(function (result) {
              // If `redirectToCheckout` fails due to a browser or network
              // error, display the localized error message to your customer
              // using `result.error.message`.
            });
          }) 
      </script>
      {% endblock %}

pro/templates/pro/thanks.html
{% extends "base.html" %}
{% load static %}
{% block content %}
<html>

  <body>
  <div class="container">
  <head><title>Thanks for your order!</title></head>
    <h1>Thanks for your order!</h1>
    <p>
      We appreciate your business!
      If you have any questions, please email
      <a href="mailto:wellnessorders@email.com">wellnessorders@email.com</a>
    </p>

     
      <div class="header clearfix">
        <nav>
          <ul class="nav nav-pills float-right">
            <li class="nav-item">
              <a class="nav-link active" href="">Home <span class="sr-only">(current)</span></a>
            </li>
          </ul>
        </nav>
        <h3 class="text-muted">Store</h3>
      </div>

      <div class="jumbotron">
        <h1 class="display-3">The Product</h1>
        <p class="lead">Access your workouts here, start your journey get strong.</p>
        <a href="{% url 'pro-members' %}"id="buy_now_btn" class="btn btn-primary">Access workouts</a>
      </div>
    </div>

  </body>
</html>
{% endblock %}