bag/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.view_bag, name='view_bag'),
    path('add/<item_id>/', views.add_to_bag, name='add_to_bag'),
    path('adjust/<item_id>/', views.adjust_bag, name='adjust_bag'),
    path('remove/<item_id>/', views.remove_from_bag, name='remove_from_bag'),
]

pro_payment/urls.py
from django.urls import path
from .views import PaymentView, EnrollView, CreateSubscriptionView, RetryInvoiceView


app_name = "pro_payment"

urlpatterns = [
    path('enroll/', EnrollView.as_view(), name='enroll'),
    path('enroll/<slug>', PaymentView.as_view(), name='payment'),
    path('create-subscription/', CreateSubscriptionView.as_view(), name='create-subscription'),
    path('retry-invoice/', RetryInvoiceView.as_view(), name='retry-invoice'),
]

videos/urls.py
from django.urls import path
from .views import CourseListView, CourseDetailView, VideoDetailView

app_name = "videos"

urlpatterns = [
    path("", CourseListView.as_view(), name='course-list'),
    path("<slug>/", CourseDetailView.as_view(), name='course-detail'),
    path("<slug>/<video_slug>/", VideoDetailView.as_view(), name='video-detail'),
]

wellness_app/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('home.urls')),
    path('products/', include('products.urls')),
    path('bag/', include('bag.urls')),
    path('checkout/', include('checkout.urls')),
    path('profile/', include('profiles.urls')),
    path('blog/', include('blog.urls')),
    path('videos/', include('videos.urls')),
    path('pro_payment/', include('pro_payment.urls')),
    path('users/', include('users.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

videos/models.py
from django.db import models
from django.conf import settings
from django.db.models.signals import pre_save, post_save
from django.utils.text import slugify
from django.shortcuts import reverse
from django.contrib.auth import get_user_model
from allauth.account.signals import email_confirmed

import stripe

stripe.api_key = settings.STRIPE_SECRET_KEY

User = get_user_model()


class Pricing(models.Model):
    """
    Model sets the price parameters of the video course
    """
    name = models.CharField(max_length=100, null=True, blank=True)  # Basic / Pro
    slug = models.SlugField(null=True)

    def __str__(self):
        return self.name


class Subscription(models.Model):
    """
    Model for subcriptions to manage each
    user subcription and permisions
    """
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    pricing = models.ForeignKey(Pricing, on_delete=models.CASCADE, related_name='subscriptions')
    created = models.DateTimeField(auto_now_add=True)
    stripe_subscription_id = models.CharField(max_length=50)
    status = models.CharField(max_length=100)

    def __str__(self):
        return self.user.email



class Course(models.Model):
    """
    Model to manage and add the courses
    """
    name = models.CharField(max_length=100, null=True, blank=True)
    slug = models.SlugField(unique=True)
    thumbnail = models.ImageField(upload_to="thumbnails/")
    description = models.TextField()

    def __str__(self):
        return self.name

    
    def get_absolute_url(self):
        return reverse("videos:course-detail", kwargs={"slug": self.slug})


class Video(models.Model):
    """
    Model for manageing and adding videos
    using vimeo, can add videos using vimeo id
    on the vimeo dashboard will generate the vimeo id needed
    """
    course = models.ForeignKey(Course, on_delete=models.CASCADE, related_name='videos')
    vimeo_id = models.CharField(max_length=50)
    title = models.CharField(max_length=150)
    slug = models.SlugField(unique=True)
    description = models.TextField()
    order = models.IntegerField(default=1)

    class Meta:
        ordering = ["order"] 

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("videos:video-detail", kwargs={
            "video_slug": self.slug,
            "slug": self.course.slug
        })


def pre_save_course(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.name)


def pre_save_video(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = slugify(instance.title)


def post_save_user(sender, instance, created, *args, **kwargs):
    if created:
        free_trial_pricing = Pricing.objects.get(name='Free Trial')
        subscription = Subscription.objects.create(
            user=instance, 
            pricing=free_trial_pricing
        )
        stripe_customer = stripe.Customer.create(
            email=instance.email
        )
        stripe_subscription = stripe.Subscription.create(
            customer=stripe_customer['id'],
            items=[{'price': 'price_1HMtRnHeew9pZh4QRDKWiRKq'}]
        )
        print(stripe_subscription)
        subscription.status = stripe_subscription["status"] # trialing
        subscription.stripe_subscription_id = stripe_subscription["id"]
        subscription.save()


post_save.connect(post_save_user, sender=User)
pre_save.connect(pre_save_course, sender=Course)
pre_save.connect(pre_save_video, sender=Video)

videos/views.py
from django.views import generic
from django.shortcuts import get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Course, Video


class CourseListView(generic.ListView):
    """
    Loads the course list from the db
    """
    template_name = "videos/course_list.html"
    queryset = Course.objects.all()


class CourseDetailView(generic.DetailView):
    """
    Loads each course detail info
    """
    template_name = "videos/course_detail.html"
    queryset = Course.objects.all()


class VideoDetailView(LoginRequiredMixin, generic.DetailView):
    """
    This function will display the video course
    for users subscribed
    """
    template_name = "videos/video_detail.html"

    def get_context_data(self, **kwargs):
        context = super(VideoDetailView, self).get_context_data(**kwargs)
        course = self.get_course()
        subscription = self.request.user
        context.update({
            "has_permission": subscription
        })
        return context

    def get_course(self):
        return get_object_or_404(Course, slug=self.kwargs["slug"])

    def get_object(self):
        video = get_object_or_404(Video, slug=self.kwargs["video_slug"])
        return video

    def get_queryset(self):
        course = self.get_course()
        return course.videos.all()

videos/templates/videos/course_detail.html
{% extends "base.html" %}
{% block content %}
<!-- Course detail page -->
    <section class="text-gray-700 body-font" style="padding-top:2rem;">
    <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap w-full mb-20">
      <div class="lg:w-1/2 w-full mb-6 lg:mb-0">
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Videos Course Details</h1>
        <div class="h-1 w-20 bg-indigo-500 rounded"></div>
      </div>
      <p class="lg:w-1/2 w-full leading-relaxed text-base">Try our free class for begginers or join us on advance yoga anytime. Get the pro memebership to stay active at home.</p>
    </div>
         <a href="{% url 'videos:course-list' %}">
    <button class="flex mx-auto mt-16 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Back to Videos Homepage</button>
    </a>
    <div class="lg:container px-5 py-18 mx-auto flex flex-wrap">
    <div class="py-16 flex flex-wrap">
        <div class="flex flex-wrap w-full">
        <div class="hidden md:block md:w-1/4 md:pr-10 md:py-6">
            {% for video in course.videos.all %}
                {% include 'videos/snippets/video_step.html' with video=video %}
            {% endfor %}
        </div>
        <div class="md:w-3/4 md:mt-0">
        <p class="text-gray-700 text-center">{{ object.description }}</p>
            <img class="w-full object-cover object-center rounded-lg" src="{{ object.thumbnail.url }}" alt="step">
        </div>
        <div class="block md:hidden w-full mt-5 py-5">
            {% for video in course.videos.all %}
                {% include 'videos/snippets/video_step.html' with video=video %}
            {% endfor %}
        </div>
    </div>
    </div>

    </section>
     <div class="lg:container  px-5 py-20 mx-auto">
        <div class="lg:w-2/3 flex flex-col sm:flex-row sm:items-center items-start mx-auto ">
        <h1 class="flex-grow sm:pr-16 text-2xl font-medium title-font text-gray-900">Join our online community and Pro today.</h1>
            <a href="{% url 'pro_payment:enroll' %}" class="flex-shrink-0 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg mt-10 sm:mt-0">
                Pro Subscription
            </a> 
        </div>
    </div>
{% endblock content %}

videos/templates/videos/course_list.html
{% extends "base.html" %}
{% block content %}
<!-- List of courses available from db -->
<section class="text-gray-700 body-font" style="padding-top:2rem;">
  <div class="container px-5 py-24 mx-auto">
    <div class="flex flex-wrap w-full mb-20">
      <div class="lg:w-1/2 w-full mb-6 lg:mb-0">
        <h1 class="sm:text-3xl text-2xl font-medium title-font mb-2 text-gray-900">Videos Course List</h1>
        <div class="h-1 w-20 bg-indigo-500 rounded"></div>
      </div>
      <p class="lg:w-1/2 w-full leading-relaxed text-base">Try our free class for begginers or join us on advance yoga anytime. Get the pro memebership to stay active at home.</p>
    </div>
    <div class="flex flex-wrap -m-4">
    {% for course in object_list %}
      <div class="xl:w-1/2 md:w-1/2 p-4">
        <div class="bg-gray-100 p-6 rounded-lg">
          <img class="h-40 rounded w-full object-cover object-center mb-6" src="{{ course.thumbnail.url }}" alt="{{ course.name }}">
          <h3 class="tracking-widest text-indigo-500 text-xs font-medium title-font">CATEGORY</h3>
          <h2 class="text-lg text-gray-900 font-medium title-font mb-4">{{ course.name }}</h2>
          <p class="leading-relaxed text-base">{{ course.description}}.</p>
           <a class="text-indigo-500 inline-flex items-center md:mb-2 lg:mb-0" href="{{ course.get_absolute_url }}">Go to course
                    <svg class="w-4 h-4 ml-2" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" fill="none" stroke-linecap="round" stroke-linejoin="round">
                    <path d="M5 12h14"></path>
                    <path d="M12 5l7 7-7 7"></path>
                    </svg>
                </a>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
</section>
{% endblock %}

videos/templates/videos/video_detail.html
{% extends "base.html" %}

{% block content %}
<!-- Video detail page displaying the vimeo video player -->
    <section class="text-gray-700 body-font" style="padding-top:4rem;">
    <h1 class="text-center" style="padding-top:2rem;">Watch Videos Here</h1>
    <div class="container py-16 flex flex-wrap">
        <div class="flex flex-wrap w-full">
        <div class="hidden md:block md:w-1/4 md:pr-10 md:py-6">
            {% for video in video.course.videos.all %}
                {% include 'videos/snippets/video_step.html' with video=video %}
            {% endfor %}
        </div>
        <div class="md:w-3/4 md:mt-0">
            {% if has_permission %}
            <iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
            {% else %}
            <p>You do not have permission to view this course. Upgrade your subscription to start</p>
            {% endif %}
        </div>
        <div class="block md:hidden w-full mt-5 py-5">
            {% for video in video.course.videos.all %}
                {% include 'videos/snippets/video_step.html' with video=video %}
            {% endfor %}
        </div>
    </div>
    </div>
      <a href="{% url 'videos:course-list' %}">
    <button class="flex mx-auto mt-16 text-white bg-indigo-500 border-0 py-2 px-8 focus:outline-none hover:bg-indigo-600 rounded text-lg">Back to Videos Homepage</button>
    </a>
    </section>
{% endblock content %}

videos/templates/videos/video_list.html
{% extends 'base.html' %}

{% block content %}
<!-- Lists of videos available -->
<div class="container" style="padding-top:6rem;">
		<div class="row">
			<div class="col-sm-4 col-md-4">
				<h1>Course List View Page</h1>
				{% for object in object_list %}
					<a href="{{ object.get_absolute_url }}">{{ object }}</a>
				{% endfor %}
			</div>
		</div>
	</div>
{% endblock %}